# Ports
set_property PACKAGE_PIN R2 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS18 [get_ports sys_clk]
set_property PACKAGE_PIN H18 [get_ports rst_n]
set_property IOSTANDARD LVCMOS18 [get_ports rst_n]
set_property PACKAGE_PIN H17 [get_ports button_1]
set_property IOSTANDARD LVCMOS18 [get_ports button_1]

set_property PACKAGE_PIN C8 [get_ports led_1]
set_property IOSTANDARD LVCMOS18 [get_ports led_1]
set_property PACKAGE_PIN D8 [get_ports led_2]
set_property IOSTANDARD LVCMOS18 [get_ports led_2]

set_property PACKAGE_PIN E17 [get_ports sda]
set_property IOSTANDARD LVCMOS18 [get_ports sda]
set_property PACKAGE_PIN C18 [get_ports scl]
set_property IOSTANDARD LVCMOS18 [get_ports sda]

set_property PACKAGE_PIN B17 [get_ports {outframe[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {outframe[0]}]
set_property PACKAGE_PIN B16 [get_ports {outframe[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {outframe[1]}]
set_property PACKAGE_PIN B15 [get_ports {outframe[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {outframe[2]}]
set_property PACKAGE_PIN B14 [get_ports {outframe[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {outframe[3]}]
set_property PACKAGE_PIN D14 [get_ports {outframe[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {outframe[4]}]
set_property PACKAGE_PIN D13 [get_ports {outframe[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {outframe[5]}]
set_property PACKAGE_PIN C12 [get_ports {outframe[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {outframe[6]}]
set_property PACKAGE_PIN E13 [get_ports {outframe[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {outframe[7]}]

# Debug

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

set_property MARK_DEBUG true [get_nets rx/logicState]
set_property MARK_DEBUG true [get_nets rx/frameReady]
set_property MARK_DEBUG true [get_nets rx/sdapulldown_i_1_n_0]

set_property MARK_DEBUG true [get_nets {frame[1]}]
set_property MARK_DEBUG true [get_nets {frame[3]}]
set_property MARK_DEBUG true [get_nets {frame[4]}]
set_property MARK_DEBUG true [get_nets {frame[0]}]
set_property MARK_DEBUG true [get_nets {frame[2]}]
set_property MARK_DEBUG true [get_nets {frame[5]}]
set_property MARK_DEBUG true [get_nets {frame[6]}]
set_property MARK_DEBUG true [get_nets {frame[7]}]
set_property MARK_DEBUG true [get_nets frameReady]
set_property MARK_DEBUG true [get_nets {rx/cframe[6]}]
set_property MARK_DEBUG true [get_nets {rx/cframe[7]}]
set_property MARK_DEBUG true [get_nets {rx/cframe[0]}]
set_property MARK_DEBUG true [get_nets {rx/cframe[1]}]
set_property MARK_DEBUG true [get_nets {rx/cframe[2]}]
set_property MARK_DEBUG true [get_nets {rx/cframe[3]}]
set_property MARK_DEBUG true [get_nets {rx/cframe[4]}]
set_property MARK_DEBUG true [get_nets {rx/cframe[5]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list sys_clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {frame[0]} {frame[1]} {frame[2]} {frame[3]} {frame[4]} {frame[5]} {frame[6]} {frame[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {rx/cframe[0]} {rx/cframe[1]} {rx/cframe[2]} {rx/cframe[3]} {rx/cframe[4]} {rx/cframe[5]} {rx/cframe[6]} {rx/cframe[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list frameReady]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list rx/logicState]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list rx/out]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list rx/sdapulldown_i_1_n_0]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets sys_clk_IBUF_BUFG]
